server:
  port: 8888

---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/{db명}?useSSL=false
    username:
    password: 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/static/
    add-mappings: true

  devtools:
    livereload:
      enabled: true
    # 실제 배포시 제거해야 함
    freemarker:
      cache: false
    # /실제 배포시 제거해야 함